name: Claim EpicGames from Container

on:
  workflow_dispatch:
  schedule:
    - cron: "10 23 * * 4,5" # Modify your timer

jobs:
  setup:
    env:
      EPIC_EMAIL: ${{ secrets.EPIC_EMAIL }}
      EPIC_PASSWORD: ${{ secrets.EPIC_PASSWORD }}
      FAKE_HASH: "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') Asia/Shanghai"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run claim-task
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        docker run --rm \
          -e EPIC_EMAIL=${{ secrets.EPIC_EMAIL }} \
          -e EPIC_PASSWORD=${{ secrets.EPIC_PASSWORD }} \
          -v ${{ github.workspace }}/user_data_dir:/home/epic/user_data_dir \
          -v ${{ github.workspace }}/logs:/home/epic/logs \
          ech0sec/awesome-epic:fish python3 claim.py

    - name: Setup gituser
      uses: fregante/setup-git-user@v1

    - name: Caching token
      run: |
        echo "${{ env.FAKE_HASH }}" > _token
        git add .
        git commit -m "${{ env.FAKE_HASH }}"
        git push -f